# Generated by Django 4.2.9 on 2025-01-22 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='capacitacion_realizada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equipo',
            name='cliente_asignado',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'CLIENTE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipo',
            name='fecha_instalacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='fecha_ultima_capacitacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='referencia',
            field=models.CharField(default='SIN-REF', max_length=100),
        ),
        migrations.AddField(
            model_name='equipo',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='equipo',
            unique_together={('referencia', 'numero_serie')},
        ),
    ]
