# Generated by Django 4.2.9 on 2025-01-22 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0002_equipo_capacitacion_realizada_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('orden', models.IntegerField(default=0)),
                ('icono', models.CharField(blank=True, max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='documents.categoriadocumento')),
            ],
            options={
                'verbose_name': 'Categoría de Documento',
                'verbose_name_plural': 'Categorías de Documentos',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('MANUAL', 'Manual de Usuario'), ('FICHA_TECNICA', 'Ficha Técnica'), ('CERTIFICADO', 'Certificado'), ('GARANTIA', 'Garantía'), ('PROCEDIMIENTO', 'Procedimiento'), ('OTRO', 'Otro')], max_length=20)),
                ('archivo', models.FileField(upload_to='documentos/')),
                ('version', models.CharField(max_length=20)),
                ('publico', models.BooleanField(default=False, help_text='Si es público, será visible para todos los usuarios')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, help_text='Tags separados por comas', max_length=500)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='documents.categoriadocumento')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_creados', to=settings.AUTH_USER_MODEL)),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_sistema', to='equipment.equipo')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='HistorialAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_accion', models.CharField(choices=[('VER', 'Ver'), ('DESCARGAR', 'Descargar'), ('EDITAR', 'Editar'), ('ELIMINAR', 'Eliminar')], max_length=20)),
                ('fecha_acceso', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('detalles', models.TextField(blank=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_accesos', to='documents.documento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_accesos_documentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Acceso',
                'verbose_name_plural': 'Historial de Accesos',
                'ordering': ['-fecha_acceso'],
            },
        ),
        migrations.CreateModel(
            name='VersionDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20)),
                ('archivo', models.FileField(upload_to='documentos/versiones/')),
                ('notas_cambios', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versiones_documentos', to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='documents.documento')),
            ],
            options={
                'verbose_name': 'Versión de Documento',
                'verbose_name_plural': 'Versiones de Documentos',
                'ordering': ['-fecha_creacion'],
                'unique_together': {('documento', 'version')},
            },
        ),
        migrations.CreateModel(
            name='PermisoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_permiso', models.CharField(choices=[('LECTURA', 'Lectura'), ('ESCRITURA', 'Escritura'), ('ADMINISTRACION', 'Administración')], max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='documents.documento')),
                ('otorgado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permisos_otorgados', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_documentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permiso de Documento',
                'verbose_name_plural': 'Permisos de Documentos',
                'unique_together': {('documento', 'usuario')},
            },
        ),
    ]
