# Generated by Django 4.2.9 on 2025-01-22 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0002_equipo_capacitacion_realizada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PREVENTIVO', 'Preventivo'), ('CORRECTIVO', 'Correctivo'), ('PREDICTIVO', 'Predictivo'), ('INSTALACION', 'Instalación'), ('CALIBRACION', 'Calibración')], max_length=20)),
                ('estado', models.CharField(choices=[('PROGRAMADO', 'Programado'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado'), ('REPROGRAMADO', 'Reprogramado')], default='PROGRAMADO', max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_programada', models.DateTimeField()),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('costo_materiales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costo_mano_obra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('diagnostico', models.TextField(blank=True)),
                ('trabajo_realizado', models.TextField(blank=True)),
                ('recomendaciones', models.TextField(blank=True)),
                ('requiere_seguimiento', models.BooleanField(default=False)),
                ('fecha_proximo_mantenimiento', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='equipment.equipo')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'ordering': ['-fecha_programada'],
            },
        ),
        migrations.CreateModel(
            name='RepuestoUsado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('numero_parte', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proveedor', models.CharField(blank=True, max_length=200)),
                ('notas', models.TextField(blank=True)),
                ('mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuestos', to='maintenance.mantenimiento')),
            ],
            options={
                'verbose_name': 'Repuesto Usado',
                'verbose_name_plural': 'Repuestos Usados',
                'ordering': ['mantenimiento', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PlanMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('frecuencia', models.CharField(choices=[('SEMANAL', 'Semanal'), ('QUINCENAL', 'Quincenal'), ('MENSUAL', 'Mensual'), ('BIMESTRAL', 'Bimestral'), ('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual')], max_length=20)),
                ('duracion_estimada', models.DurationField(help_text='Duración estimada del mantenimiento')),
                ('procedimiento', models.TextField(help_text='Procedimiento detallado del mantenimiento')),
                ('herramientas_requeridas', models.TextField(blank=True)),
                ('materiales_requeridos', models.TextField(blank=True)),
                ('requiere_tecnico_especializado', models.BooleanField(default=False)),
                ('notas', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_mantenimiento', to='equipment.equipo')),
            ],
            options={
                'verbose_name': 'Plan de Mantenimiento',
                'verbose_name_plural': 'Planes de Mantenimiento',
                'ordering': ['equipo', 'frecuencia'],
            },
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos', to='maintenance.planmantenimiento'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='tecnico_asignado',
            field=models.ForeignKey(limit_choices_to={'tipo': 'TECNICO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FotoMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='mantenimientos/')),
                ('descripcion', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('ANTES', 'Antes del mantenimiento'), ('DURANTE', 'Durante el mantenimiento'), ('DESPUES', 'Después del mantenimiento'), ('PROBLEMA', 'Problema encontrado'), ('OTRO', 'Otro')], max_length=50)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='maintenance.mantenimiento')),
            ],
            options={
                'verbose_name': 'Foto de Mantenimiento',
                'verbose_name_plural': 'Fotos de Mantenimiento',
                'ordering': ['mantenimiento', 'fecha_subida'],
            },
        ),
    ]
